### ISSUE TITLE
Issue with percentages

### ISSUE THREAD

**Issue by msidqi** [estarossa0/transcendence#2]
There is an issue with the % shown in the project
![image](https://user-images.githubusercontent.com/42954251/137025342-9f60a752-dabc-45c4-88f3-ffaab6f143c4.png)

**Comment by oxidia** [comment]
Indeed
@estarossa0, Could you change this to 100% ts

**Comment by estarossa0** [comment]
@msidqi @oxidia this was already fixed in dev, just wait for the next release

**Comment by estarossa0** [comment]
@oxidia @msidqi  LGTM
![image](https://user-images.githubusercontent.com/57002508/137531888-8951d622-b5c3-40d7-b357-0f15556f9cca.png)

**Comment by estarossa0** [comment]
@msidqi @oxidia unfortunately this will be back in next releaser as nextjs doesn't support `next.config.ts` but `next.config.js` only, as it slow bootup for both prod and dev.
for more about the reason please head to this issue ([LINK](https://github.com/vercel/next.js/issues/5318))
